ato/urls.py
from django.conf.urls import url
from ato.views import TrainingList, TrainingDetails, TrainingCreate, TrainingUpdate, TrainingDelete
from ato.views import PhaseDetails, PhaseCreate, PhaseUpdate, PhaseDelete
from ato.views import ExerciseDetails, ExerciseCreate, ExerciseUpdate, ExerciseDelete
from ato.views import InstructorList, InstructorCreate, InstructorUpdate, InstructorDelete
from ato.views import InstructorInfo, InstructorFlights, InstructorTrainings
from ato.views import StudentList, StudentCreate, StudentUpdate, StudentDelete
from ato.views import StudentInfo, StudentFlights, StudentTrainings
from ato.views import TrainingInstList, TrainingInstDetails, TrainingInstCreate, TrainingInstUpdate, TrainingInstDelete, TrainingInstPass
from ato.views import PhaseInstDetails, PhaseInstCreate, PhaseInstUpdate, PhaseInstDelete, PhaseInstPass
from ato.views import ExerciseInstDetails, ExerciseInstCreate, ExerciseInstUpdate, ExerciseInstDelete, ExerciseInstPass
from ato.views import ExerciseOperCreate, ExerciseOperUpdate, ExerciseOperDelete
from ato.views import CardEntryList, CardReport, CardEntryDetails, CardEntryCreate, CardEntryUpdate, CardEntryDelete


from ato.loaders import update_phases

urlpatterns = [

    url(r'^$', TrainingInstList.as_view(), name='training-inst-list'),
    url(r'^trinst/details/(?P<pk>\d+)/$', TrainingInstDetails.as_view(), name='training-inst-details'),
    url(r'^trinst/create/$', TrainingInstCreate, name='training-inst-create'),
    url(r'^trinst/update/(?P<pk>\d+)/$', TrainingInstUpdate.as_view(), name='training-inst-update'),
    url(r'^trinst/delete/(?P<pk>\d+)/$', TrainingInstDelete.as_view(), name='training-inst-delete'),
    url(r'^trinst/pass/(?P<pk>\d+)/$', TrainingInstPass, name='training-inst-pass'),

    url(r'^phinst/details/(?P<pk>\d+)/$', PhaseInstDetails.as_view(), name='phase-inst-details'),
    url(r'^phinst/create/(?P<training_inst_id>\d+)/$', PhaseInstCreate.as_view(), name='phase-inst-create'),
    url(r'^phinst/update/(?P<pk>\d+)/$', PhaseInstUpdate.as_view(), name='phase-inst-update'),
    url(r'^phinst/delete/(?P<pk>\d+)/$', PhaseInstDelete.as_view(), name='phase-inst-delete'),
    url(r'^phinst/pass/(?P<pk>\d+)/$', PhaseInstPass, name='phase-inst-pass'),

    url(r'^exinst/details/(?P<pk>\d+)/$', ExerciseInstDetails.as_view(), name='exercise-inst-details'),
    url(r'^exinst/create/(?P<phase_inst_id>\d+)/$', ExerciseInstCreate.as_view(), name='exercise-inst-create'),
    url(r'^exinst/update/(?P<pk>\d+)/$', ExerciseInstUpdate.as_view(), name='exercise-inst-update'),
    url(r'^exinst/delete/(?P<pk>\d+)/$', ExerciseInstDelete.as_view(), name='exercise-inst-delete'),
    url(r'^exinst/pass/(?P<pk>\d+)/$', ExerciseInstPass, name='exercise-inst-pass'),

    url(r'^exoper/create/(?P<exercise_inst_id>\d+)/$', ExerciseOperCreate, name='exercise-oper-create'),
    url(r'^exoper/update/(?P<pk>\d+)/$', ExerciseOperUpdate.as_view(), name='exercise-oper-update'),
    url(r'^exoper/delete/(?P<pk>\d+)/$', ExerciseOperDelete.as_view(), name='exercise-oper-delete'),

    url(r'^card/list/(?P<training_inst_id>\d+)/$', CardEntryList.as_view(), name='card-entry-list'),
    url(r'^card/report/(?P<training_inst_id>\d+)/$', CardReport.as_view(), name='card-report'),
    url(r'^card/details/(?P<pk>\d+)/$', CardEntryDetails.as_view(), name='card-entry-details'),
    url(r'^card/create/(?P<training_inst_id>\d+)/$', CardEntryCreate.as_view(), name='card-entry-create'),
    url(r'^card/update/(?P<pk>\d+)/$', CardEntryUpdate.as_view(), name='card-entry-update'),
    url(r'^card/delete/(?P<pk>\d+)/$', CardEntryDelete.as_view(), name='card-entry-delete'),

    url(r'^training/list/$', TrainingList.as_view(), name='training-list'),
    url(r'^training/details/(?P<pk>\d+)/$', TrainingDetails.as_view(), name='training-details'),
    url(r'^training/create/$', TrainingCreate.as_view(), name='training-create'),
    url(r'^training/update/(?P<pk>\d+)/$', TrainingUpdate.as_view(), name='training-update'),
    url(r'^training/delete/(?P<pk>\d+)/$', TrainingDelete.as_view(), name='training-delete'),

    url(r'^phase/details/(?P<pk>\d+)/$', PhaseDetails.as_view(), name='phase-details'),
    url(r'^phase/create/(?P<training_id>\d+)/$', PhaseCreate.as_view(), name='phase-create'),
    url(r'^phase/update/(?P<pk>\d+)/$', PhaseUpdate.as_view(), name='phase-update'),
    url(r'^phase/delete/(?P<pk>\d+)/$', PhaseDelete.as_view(), name='phase-delete'),

    url(r'^exercise/details/(?P<pk>\d+)/$', ExerciseDetails.as_view(), name='exercise-details'),
    url(r'^exercise/create/(?P<phase_id>\d+)/$', ExerciseCreate.as_view(), name='exercise-create'),
    url(r'^exercise/update/(?P<pk>\d+)/$', ExerciseUpdate.as_view(), name='exercise-update'),
    url(r'^exercise/delete/(?P<pk>\d+)/$', ExerciseDelete.as_view(), name='exercise-delete'),

    url(r'^instructor/list/$', InstructorList.as_view(), name='instr-list'),
    url(r'^instructor/info/(?P<pk>\d+)/$', InstructorInfo.as_view(), name='instr-info'),
    url(r'^instructor/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', InstructorTrainings.as_view(), name='instr-trainings'),
    url(r'^instructor/flights/(?P<pk>\d+)/$', InstructorFlights.as_view(), name='instr-flights'),
    url(r'^instructor/create/$', InstructorCreate.as_view(), name='instr-create'),
    url(r'^instructor/update/(?P<pk>\d+)/$', InstructorUpdate.as_view(), name='instr-update'),
    url(r'^instructor/delete/(?P<pk>\d+)/$', InstructorDelete.as_view(), name='instr-delete'),

    url(r'^student/list/$', StudentList.as_view(), name='student-list'),
    url(r'^student/info/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-info'),
    url(r'^student/flights/(?P<pk>\d+)/$', StudentFlights.as_view(), name='student-flights'),
    url(r'^student/account/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-account'),
    url(r'^student/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', StudentTrainings.as_view(), name='student-trainings'),
    url(r'^student/create/$', StudentCreate.as_view(), name='student-create'),
    url(r'^student/update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student-update'),
    url(r'^student/delete/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student-delete'),

    url(r'^_update/$', update_phases, name='update-phases'),

]

fin/urls.py
from django.conf.urls import url
from fin.views import FuelTanktList, FuelTankCreate, FuelTankUpdate, FuelTankDelete
from fin.views import FuelTankInfo, FuelTankDeliveries, FuelTankTransfers, FuelTankCorrections
from fin.views import FuelTankFuelings, FuelTankPDTFuelings
from fin.views import DeliveryDetails, DeliveryCreate, DeliveryUpdate, DeliveryDelete
from fin.views import TransferDetails, TransferCreate, TransferUpdate, TransferDelete
from fin.views import CorrectionDetails, CorrectionCreate, CorrectionUpdate, CorrectionDelete
from fin.views import FuelingDetails, FuelingCreate, FuelingUpdate, FuelingDelete
from fin.views import PDTFuelingDetails, PDTFuelingUpdate, PDTFuelingDelete
from fin.views import VoucherList, VoucherDetails, VoucherCreate, VoucherUpdate, VoucherDelete, VoucherDoneList
from fin.views import RentPackageList, RentPackageDetails, RentPackageCreate, RentPackageUpdate, RentPackageDelete
from fin.views import RentPriceList, RentPriceUpdate
from fin.views import PackageBuy, PackageSell
from fin.views import ContactorList, ContractorInfo, ContractorCreate, ContractorUpdate, ContractorDelete
from fin.views import ContractorOperations, ContractorPackages, ContractorFlights, ContractorFuelings
from fin.views import RemoteFuelingDetails, RemoteFuelingUpdate, RemoteFuelingDelete
from fin.views import BalanceOperationDetails, BalanceOperationCreate, BalanceOperationUpdate, BalanceOperationDelete
from fin.views import PriceCreate, PriceUpdate, PriceDelete
from fin.views import FuelReport, FuelExport
from fin.views import PDTList, PDT_feed
from fin.loaders import update_contr

urlpatterns = [

    url(r'^fueltank/list/$', FuelTanktList.as_view(), name='tank-list'),
    url(r'^fueltank/info/(?P<pk>\d+)/$', FuelTankInfo.as_view(), name='tank-info'),
    url(r'^fueltank/deliveries/(?P<pk>\d+)/$', FuelTankDeliveries.as_view(), name='tank-deliveries'),
    url(r'^fueltank/transfers/(?P<type>\w+)/(?P<pk>\d+)/$', FuelTankTransfers.as_view(), name='tank-transfers'),
    url(r'^fueltank/corrections/(?P<pk>\d+)/$', FuelTankCorrections.as_view(), name='tank-corrections'),
    url(r'^fueltank/fuelings/(?P<pk>\d+)/$', FuelTankFuelings.as_view(), name='tank-fuelings'),
    url(r'^fueltank/pdtfuelings/(?P<pk>\d+)/$', FuelTankPDTFuelings.as_view(), name='tank-pdt-fuelings'),
    url(r'^fueltank/create/$', FuelTankCreate.as_view(), name='tank-create'),
    url(r'^fueltank/update/(?P<pk>\d+)/$', FuelTankUpdate.as_view(), name='tank-update'),
    url(r'^fueltank/delete/(?P<pk>\d+)/$', FuelTankDelete.as_view(), name='tank-delete'),

    url(r'^pdt/list/$', PDTList.as_view(), name='pdt-list'),
    url(r'^pdt/feed/$', PDT_feed.as_view(), name='pdt-feed'),

    url(r'^delivery/details/(?P<pk>\d+)/$', DeliveryDetails.as_view(), name='delivery-details'),
    url(r'^delivery/create/(?P<fueltank_id>\d+)/$', DeliveryCreate.as_view(), name='delivery-create'),
    url(r'^delivery/update/(?P<pk>\d+)/$', DeliveryUpdate.as_view(), name='delivery-update'),
    url(r'^delivery/delete/(?P<pk>\d+)/$', DeliveryDelete.as_view(), name='delivery-delete'),

    url(r'^transfer/details/(?P<type>\w+)/(?P<pk>\d+)/$', TransferDetails.as_view(), name='transfer-details'),
    url(r'^transfer/create/(?P<type>\w+)/(?P<fueltank_id>\d+)/$', TransferCreate.as_view(), name='transfer-create'),
    url(r'^transfer/update/(?P<type>\w+)/(?P<pk>\d+)/$', TransferUpdate.as_view(), name='transfer-update'),
    url(r'^transfer/delete/(?P<type>\w+)/(?P<pk>\d+)/$', TransferDelete.as_view(), name='transfer-delete'),

    url(r'^correction/details/(?P<pk>\d+)/$', CorrectionDetails.as_view(), name='correction-details'),
    url(r'^correction/create/(?P<fueltank_id>\d+)/$', CorrectionCreate.as_view(), name='correction-create'),
    url(r'^correction/update/(?P<pk>\d+)/$', CorrectionUpdate.as_view(), name='correction-update'),
    url(r'^correction/delete/(?P<pk>\d+)/$', CorrectionDelete.as_view(), name='correction-delete'),

    url(r'^fueling/details/(?P<pk>\d+)/$', FuelingDetails.as_view(), name='fueling-details'),
    url(r'^fueling/create/(?P<fueltank_id>\d+)/$', FuelingCreate.as_view(), name='fueling-create'),
    url(r'^fueling/update/(?P<pk>\d+)/$', FuelingUpdate.as_view(), name='fueling-update'),
    url(r'^fueling/delete/(?P<pk>\d+)/$', FuelingDelete.as_view(), name='fueling-delete'),

    url(r'^remotefueling/details/(?P<pk>\d+)/$', RemoteFuelingDetails.as_view(), name='remote-fueling-details'),
    url(r'^remotefueling/update/(?P<pk>\d+)/$', RemoteFuelingUpdate.as_view(), name='remote-fueling-update'),
    url(r'^remotefueling/delete/(?P<pk>\d+)/$', RemoteFuelingDelete.as_view(), name='remote-fueling-delete'),

    url(r'^pdtfueling/details/(?P<pk>\d+)/$', PDTFuelingDetails.as_view(), name='pdtfueling-details'),
    url(r'^pdtfueling/update/(?P<pk>\d+)/$', PDTFuelingUpdate.as_view(), name='pdtfueling-update'),
    url(r'^pdtfueling/delete/(?P<pk>\d+)/$', PDTFuelingDelete.as_view(), name='pdtfueling-delete'),

    url(r'^voucher/list/$', VoucherList.as_view(), name='voucher-list'),
    url(r'^voucher/done/$', VoucherDoneList.as_view(), name='voucher-done'),
    url(r'^voucher/details/(?P<pk>\d+)/$', VoucherDetails.as_view(), name='voucher-details'),
    url(r'^voucher/create/$', VoucherCreate.as_view(), name='voucher-create'),
    url(r'^voucher/update/(?P<pk>\d+)/$', VoucherUpdate.as_view(), name='voucher-update'),
    url(r'^voucher/delete/(?P<pk>\d+)/$', VoucherDelete.as_view(), name='voucher-delete'),

    url(r'^$', ContactorList.as_view(), name='contr-list'),
    url(r'^contractor/info/(?P<pk>\d+)/$', ContractorInfo.as_view(), name='contr-info'),
    url(r'^contractor/operations/(?P<pk>\d+)/$', ContractorOperations.as_view(), name='contr-operations'),
    url(r'^contractor/packages/(?P<pk>\d+)/$', ContractorPackages.as_view(), name='contr-packages'),
    url(r'^contractor/flights/(?P<type>\w+)/(?P<pk>\d+)/$', ContractorFlights.as_view(), name='contr-flights'),
    url(r'^contractor/fuelings/(?P<pk>\d+)/$', ContractorFuelings.as_view(), name='contr-fuelings'),
    url(r'^contractor/create/$', ContractorCreate.as_view(), name='contr-create'),
    url(r'^contractor/update/(?P<pk>\d+)/$', ContractorUpdate.as_view(), name='contr-update'),
    url(r'^contractor/delete/(?P<pk>\d+)/$', ContractorDelete.as_view(), name='contr-delete'),

    url(r'^package/list/$', RentPackageList.as_view(), name='package-list'),
    url(r'^package/details/(?P<pk>\d+)/$', RentPackageDetails.as_view(), name='package-details'),
    url(r'^package/create/$', RentPackageCreate.as_view(), name='package-create'),
    url(r'^package/update/(?P<pk>\d+)/$', RentPackageUpdate.as_view(), name='package-update'),
    url(r'^package/delete/(?P<pk>\d+)/$', RentPackageDelete.as_view(), name='package-delete'),
    url(r'^package/buy/(?P<contractor_id>\d+)/$', PackageBuy, name='package-buy'),
    url(r'^package/sell/(?P<pk>\d+)/$', PackageSell.as_view(), name='package-sell'),

    url(r'^operation/details/(?P<pk>\d+)/$', BalanceOperationDetails.as_view(), name='operation-details'),
    url(r'^operation/create/(?P<contractor_id>\d+)/$', BalanceOperationCreate.as_view(), name='operation-create'),
    url(r'^operation/update/(?P<pk>\d+)/$', BalanceOperationUpdate.as_view(), name='operation-update'),
    url(r'^operation/delete/(?P<pk>\d+)/$', BalanceOperationDelete.as_view(), name='operation-delete'),

    url(r'^rentprice/list/$', RentPriceList.as_view(), name='rentprice-list'),
    url(r'^rentprice/update/(?P<pk>\d+)/$', RentPriceUpdate.as_view(), name='rentprice-update'),

    url(r'^price/create/(?P<contractor_id>\d+)/$', PriceCreate.as_view(), name='price-create'),
    url(r'^price/update/(?P<pk>\d+)/$', PriceUpdate.as_view(), name='price-update'),
    url(r'^price/delete/(?P<pk>\d+)/$', PriceDelete.as_view(), name='price-delete'),

    url(r'^fuel/report/$', FuelReport, name='fuel-report'),
    url(r'^fuel/export/(?P<type>\d+)/(?P<report_start>\d{4}-\d{2}-\d{2})/(?P<report_end>\d{4}-\d{2}-\d{2})/$', FuelExport, name='fuel-export'),

    url(r'^_contr/$', update_contr, name='update_contr'),

]

salt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, logout_then_login
from salt.views import dispatcher, salt_login, salt_password_change, admin_password_change

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^panel/', include('panel.urls', namespace="panel")),
    url(r'^camo/', include('camo.urls', namespace="camo")),
    url(r'^pdt/', include('pdt.urls', namespace="pdt")),
    url(r'^sms/', include('sms.urls', namespace="sms")),
    url(r'^ato/', include('ato.urls', namespace="ato")),
    url(r'^fin/', include('fin.urls', namespace="fin")),
    url(r'^fbo/', include('fbo.urls', namespace="fbo")),
    url(r'^res/', include('res.urls', namespace="res")),

    url(r'^login/$', salt_login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'dispatcher'}, name='logout'),
    url(r'^password/$', salt_password_change, {'post_change_redirect': 'dispatcher'}, name='pwd-change'),
    url(r'^adminpwd/(?P<user_id>\d+)/$', admin_password_change, name='admin-pwd-change'),
    url(r'^$', dispatcher, name='dispatcher'),
]

admin.site.site_header = 'Administracja systemu SALT'

salt/models.py
from django.db import models
from salt.forms import MyDurationFormField


class MyDurationField(models.DurationField):

    description = 'Simplified Duration Field'

    def formfield(self, **kwargs):
        defaults = {'form_class': MyDurationFormField}
        defaults.update(kwargs)
        return super(MyDurationField, self).formfield(**defaults)

fin/forms.py
# -*- coding: utf-8 -*-

from django import forms
from datetime import date
from fin.models import RentPackage
from django.contrib.admin.widgets import AdminDateWidget
from django.forms import Textarea, TextInput
from django.core.exceptions import ValidationError


class PackageBuyForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.contractor = kwargs.pop('contractor')
        super(PackageBuyForm, self).__init__(*args, **kwargs)
        choices = []
        for package in RentPackage.objects.all():
            label = ''
            label += '<td style="text-align: center"><b>%s</b></td>' % package.package_id
            label += '<td>%s</td>' % package.name
            label += '<td style="text-align: center">%s</td>' % package.ac_type
            label += '<td style="text-align: center">%d</td>' % package.hours
            label += '<td style="text-align: center">%.2f PLN</td>' % package.hour_price
            label += '<td>%s</td>' % package.remarks
            choices.append ((package.pk, label))

        self.fields['packages'] = forms.ChoiceField(choices=choices, widget=forms.RadioSelect())
        self.fields['packages'].error_messages['required'] = 'Należy wybrać pakiet!'
        self.fields['packages'].error_messages['no_money'] = 'Brak środków na rachunku!'

        self.fields['date'] = forms.DateField(widget=AdminDateWidget())
        self.fields['date'].initial = date.today()

        self.fields['remarks'] = forms.CharField(widget=Textarea(attrs={'rows':2, 'cols':100}))
        self.fields['remarks'].required = False

    def clean_packages(self, **kwargs):
        cleaned_data = super(PackageBuyForm, self).clean()
        package = RentPackage.objects.get(pk = cleaned_data['packages'])
        if self.contractor.rent_balance < package.hours * package.hour_price:
            raise ValidationError(('Zbyt mało środków na rachunku!'), code='no_money')
        return cleaned_data['packages']

salt/templates/fin/contr_operations.html
{% extends 'fin/list_template.html' %}

{% load staticfiles %}

{% block presection %}

    <div class="pure-u">

        <h2>Aktualne salda dla {{ contractor.name }}</h2>

        <table id="data-table">
            <tr>
                <th>Saldo szkoleń</th>
                <td class="balance {% if contractor.ato_balance < 0 %} negative{% endif %}">{{ contractor.ato_balance|floatformat:2 }} PLN</td>
            </tr>
            <tr>
                <th>Saldo wynajmu</th>
                <td class="balance {% if contractor.rent_balance < 0 %} negative{% endif %}">{{ contractor.rent_balance|floatformat:2 }} PLN</td>
            </tr>
            <tr>
                <th>Saldo AOC</th>
                <td class="balance {% if contractor.aoc_balance < 0 %} negative{% endif %}">{{ contractor.aoc_balance|floatformat:2 }} PLN</td>
            </tr>
            <tr>
                <th>Saldo usług</th>
                <td class="balance {% if contractor.spo_balance < 0 %} negative{% endif %}">{{ contractor.spo_balance|floatformat:2 }} PLN</td>
            </tr>
        </table>
        <br>

    </div>

{% endblock %}

salt/templates/fin/contr_submenu.html
<div class="pure-u-1-6">

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item {% if type == 'info' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-info' contractor.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ contractor.contractor_id }}</b></a></li>
            <li class="pure-menu-item {% if type == 'operations' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-operations' contractor.pk %}" class="pure-menu-link">Salda i operacje</a></li>
            <li class="pure-menu-item {% if type == 'packages' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-packages' contractor.pk %}" class="pure-menu-link">Pakiety i ceny specjalne</a></li>
            <li class="pure-menu-item {% if type == 'ato' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-flights' 'ato' contractor.pk %}" class="pure-menu-link">Loty szkoleniowe</a></li>
            <li class="pure-menu-item {% if type == 'rent' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-flights' 'rent' contractor.pk %}" class="pure-menu-link">Loty w wynajmie</a></li>
            <li class="pure-menu-item {% if type == 'aoc' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-flights' 'aoc' contractor.pk %}" class="pure-menu-link">Loty AOC</a></li>
            <li class="pure-menu-item {% if type == 'spo' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-flights' 'spo' contractor.pk %}" class="pure-menu-link">Loty SPO</a></li>
            <li class="pure-menu-item {% if type == 'fuelings' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:contr-fuelings' contractor.pk %}" class="pure-menu-link">Tankowania poza SALT</a></li>
        </ul>
    </div>

</div>

salt/templates/fin/fin_template.html
{% extends 'salt_template.html' %}

{% block title %}FINANSE{% endblock %}

{% block module %}FINANSE I PALIWO{% endblock %}

{% block menu %}
    <li class="pure-menu-item"><a href="{% url 'fin:tank-list' %}" class="pure-menu-link">Paliwo</a></li>
    <li class="pure-menu-item"><a href="{% url 'fin:pdt-list' %}" class="pure-menu-link">PDTy</a></li>
    <li class="pure-menu-item"><a href="{% url 'fin:contr-list' %}" class="pure-menu-link">Kontrahenci</a></li>
    <li class="pure-menu-item"><a href="{% url 'fin:voucher-list' %}" class="pure-menu-link">Vouchery</a></li>
    <li class="pure-menu-item"><a href="{% url 'fin:rentprice-list' %}" class="pure-menu-link">Cennik wynajmu</a></li>
    <li class="pure-menu-item"><a href="{% url 'fin:package-list' %}" class="pure-menu-link">Pakiety wynajmu</a></li>
{% endblock %}

salt/templates/fin/tank_submenu.html
<div class="pure-u-1-6">

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item {% if type == 'info' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-info' tank.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ tank.tank_ref }}</b></a></li>
            <li class="pure-menu-item {% if type == 'deliveries' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-deliveries' tank.pk %}" class="pure-menu-link">Dostawy paliwa</a></li>
            <li class="pure-menu-item {% if type == 'intrans' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-transfers' 'in' tank.pk %}" class="pure-menu-link">Wydania do zbiornika</a></li>
            <li class="pure-menu-item {% if type == 'outtrans' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-transfers' 'out' tank.pk %}" class="pure-menu-link">Wydania ze zbiornika</a></li>
            <li class="pure-menu-item {% if type == 'corrections' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-corrections' tank.pk %}" class="pure-menu-link">Potokoły różnic</a></li>
            <li class="pure-menu-item {% if type == 'pdtfuelings' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-pdt-fuelings' tank.pk %}" class="pure-menu-link">Tankowania SP</a></li>
            <li class="pure-menu-item {% if type == 'fuelings' %}pure-menu-selected{% endif %}">
                <a href="{% url 'fin:tank-fuelings' tank.pk %}" class="pure-menu-link">Tankowania bez PDT</a></li>
        </ul>
    </div>

</div>