ato/urls.py
from django.conf.urls import url
from ato.views import TrainingList, TrainingDetails, TrainingCreate, TrainingUpdate, TrainingDelete
from ato.views import PhaseDetails, PhaseCreate, PhaseUpdate, PhaseDelete
from ato.views import ExerciseDetails, ExerciseCreate, ExerciseUpdate, ExerciseDelete
from ato.views import InstructorList, InstructorCreate, InstructorUpdate, InstructorDelete
from ato.views import InstructorInfo, InstructorFlights, InstructorTrainings
from ato.views import StudentList, StudentCreate, StudentUpdate, StudentDelete
from ato.views import StudentInfo, StudentFlights, StudentTrainings
from ato.views import TrainingInstList, TrainingInstDetails, TrainingInstCreate, TrainingInstUpdate, TrainingInstDelete, TrainingInstPass
from ato.views import PhaseInstDetails, PhaseInstCreate, PhaseInstUpdate, PhaseInstDelete, PhaseInstPass
from ato.views import ExerciseInstDetails, ExerciseInstCreate, ExerciseInstUpdate, ExerciseInstDelete, ExerciseInstPass
from ato.views import ExerciseOperCreate, ExerciseOperUpdate, ExerciseOperDelete
from ato.views import CardEntryList, CardReport, CardEntryDetails, CardEntryCreate, CardEntryUpdate, CardEntryDelete


from ato.loaders import update_phases

urlpatterns = [

    url(r'^$', TrainingInstList.as_view(), name='training-inst-list'),
    url(r'^trinst/details/(?P<pk>\d+)/$', TrainingInstDetails.as_view(), name='training-inst-details'),
    url(r'^trinst/create/$', TrainingInstCreate, name='training-inst-create'),
    url(r'^trinst/update/(?P<pk>\d+)/$', TrainingInstUpdate.as_view(), name='training-inst-update'),
    url(r'^trinst/delete/(?P<pk>\d+)/$', TrainingInstDelete.as_view(), name='training-inst-delete'),
    url(r'^trinst/pass/(?P<pk>\d+)/$', TrainingInstPass, name='training-inst-pass'),

    url(r'^phinst/details/(?P<pk>\d+)/$', PhaseInstDetails.as_view(), name='phase-inst-details'),
    url(r'^phinst/create/(?P<training_inst_id>\d+)/$', PhaseInstCreate.as_view(), name='phase-inst-create'),
    url(r'^phinst/update/(?P<pk>\d+)/$', PhaseInstUpdate.as_view(), name='phase-inst-update'),
    url(r'^phinst/delete/(?P<pk>\d+)/$', PhaseInstDelete.as_view(), name='phase-inst-delete'),
    url(r'^phinst/pass/(?P<pk>\d+)/$', PhaseInstPass, name='phase-inst-pass'),

    url(r'^exinst/details/(?P<pk>\d+)/$', ExerciseInstDetails.as_view(), name='exercise-inst-details'),
    url(r'^exinst/create/(?P<phase_inst_id>\d+)/$', ExerciseInstCreate.as_view(), name='exercise-inst-create'),
    url(r'^exinst/update/(?P<pk>\d+)/$', ExerciseInstUpdate.as_view(), name='exercise-inst-update'),
    url(r'^exinst/delete/(?P<pk>\d+)/$', ExerciseInstDelete.as_view(), name='exercise-inst-delete'),
    url(r'^exinst/pass/(?P<pk>\d+)/$', ExerciseInstPass, name='exercise-inst-pass'),

    url(r'^exoper/create/(?P<exercise_inst_id>\d+)/$', ExerciseOperCreate, name='exercise-oper-create'),
    url(r'^exoper/update/(?P<pk>\d+)/$', ExerciseOperUpdate.as_view(), name='exercise-oper-update'),
    url(r'^exoper/delete/(?P<pk>\d+)/$', ExerciseOperDelete.as_view(), name='exercise-oper-delete'),

    url(r'^card/list/(?P<training_inst_id>\d+)/$', CardEntryList.as_view(), name='card-entry-list'),
    url(r'^card/report/(?P<training_inst_id>\d+)/$', CardReport.as_view(), name='card-report'),
    url(r'^card/details/(?P<pk>\d+)/$', CardEntryDetails.as_view(), name='card-entry-details'),
    url(r'^card/create/(?P<training_inst_id>\d+)/$', CardEntryCreate.as_view(), name='card-entry-create'),
    url(r'^card/update/(?P<pk>\d+)/$', CardEntryUpdate.as_view(), name='card-entry-update'),
    url(r'^card/delete/(?P<pk>\d+)/$', CardEntryDelete.as_view(), name='card-entry-delete'),

    url(r'^training/list/$', TrainingList.as_view(), name='training-list'),
    url(r'^training/details/(?P<pk>\d+)/$', TrainingDetails.as_view(), name='training-details'),
    url(r'^training/create/$', TrainingCreate.as_view(), name='training-create'),
    url(r'^training/update/(?P<pk>\d+)/$', TrainingUpdate.as_view(), name='training-update'),
    url(r'^training/delete/(?P<pk>\d+)/$', TrainingDelete.as_view(), name='training-delete'),

    url(r'^phase/details/(?P<pk>\d+)/$', PhaseDetails.as_view(), name='phase-details'),
    url(r'^phase/create/(?P<training_id>\d+)/$', PhaseCreate.as_view(), name='phase-create'),
    url(r'^phase/update/(?P<pk>\d+)/$', PhaseUpdate.as_view(), name='phase-update'),
    url(r'^phase/delete/(?P<pk>\d+)/$', PhaseDelete.as_view(), name='phase-delete'),

    url(r'^exercise/details/(?P<pk>\d+)/$', ExerciseDetails.as_view(), name='exercise-details'),
    url(r'^exercise/create/(?P<phase_id>\d+)/$', ExerciseCreate.as_view(), name='exercise-create'),
    url(r'^exercise/update/(?P<pk>\d+)/$', ExerciseUpdate.as_view(), name='exercise-update'),
    url(r'^exercise/delete/(?P<pk>\d+)/$', ExerciseDelete.as_view(), name='exercise-delete'),

    url(r'^instructor/list/$', InstructorList.as_view(), name='instr-list'),
    url(r'^instructor/info/(?P<pk>\d+)/$', InstructorInfo.as_view(), name='instr-info'),
    url(r'^instructor/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', InstructorTrainings.as_view(), name='instr-trainings'),
    url(r'^instructor/flights/(?P<pk>\d+)/$', InstructorFlights.as_view(), name='instr-flights'),
    url(r'^instructor/create/$', InstructorCreate.as_view(), name='instr-create'),
    url(r'^instructor/update/(?P<pk>\d+)/$', InstructorUpdate.as_view(), name='instr-update'),
    url(r'^instructor/delete/(?P<pk>\d+)/$', InstructorDelete.as_view(), name='instr-delete'),

    url(r'^student/list/$', StudentList.as_view(), name='student-list'),
    url(r'^student/info/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-info'),
    url(r'^student/flights/(?P<pk>\d+)/$', StudentFlights.as_view(), name='student-flights'),
    url(r'^student/account/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-account'),
    url(r'^student/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', StudentTrainings.as_view(), name='student-trainings'),
    url(r'^student/create/$', StudentCreate.as_view(), name='student-create'),
    url(r'^student/update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student-update'),
    url(r'^student/delete/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student-delete'),

    url(r'^_update/$', update_phases, name='update-phases'),

]

res/urls.py
from django.conf.urls import url
from res.views import ResourceFBOList, ResourceFBOCreate, ResourceFBOUpdate, ResourceFBODelete
from res.views import ReservationList, ReservationInfo, ReservationCreate, ReservationUpdate, ReservationDelete
from res.views import ReservationFBOInfo, ReservationFBOCreate, ReservationFBOUpdate, ReservationFBODelete
from res.views import BlackoutList, BlackoutInfo, BlackoutCreate, BlackoutUpdate, BlackoutDelete
from res.views import ResParamsList, ResParamsUpdate
from res.views import ReservationCalendar, DutyCalendar, reservation_feed, reservation_move, duty_feed
from res.views import ReservationListMobile

urlpatterns = [

    url(r'^reservation/list/$', ReservationList, name='reservation-list'),
    url(r'^reservation/info/(?P<pk>\d+)/$', ReservationInfo.as_view(), name='reservation-info'),
    url(r'^reservation/create/$', ReservationCreate.as_view(), name='reservation-create'),
    url(r'^reservation/update/(?P<pk>\d+)/$', ReservationUpdate.as_view(), name='reservation-update'),
    url(r'^reservation/delete/(?P<pk>\d+)/$', ReservationDelete.as_view(), name='reservation-delete'),

    url(r'^resource/list/$', ResourceFBOList.as_view(), name='resource-list'),
    url(r'^resource/create/$', ResourceFBOCreate.as_view(), name='resource-create'),
    url(r'^resource/update/(?P<pk>\d+)/$', ResourceFBOUpdate.as_view(), name='resource-update'),
    url(r'^resource/delete/(?P<pk>\d+)/$', ResourceFBODelete.as_view(), name='resource-delete'),

    url(r'^resfbo/info/(?P<pk>\d+)/$', ReservationFBOInfo.as_view(), name='resfbo-info'),
    url(r'^resfbo/create/$', ReservationFBOCreate.as_view(), name='resfbo-create'),
    url(r'^resfbo/update/(?P<pk>\d+)/$', ReservationFBOUpdate.as_view(), name='resfbo-update'),
    url(r'^resfbo/delete/(?P<pk>\d+)/$', ReservationFBODelete.as_view(), name='resfbo-delete'),

    url(r'^blackout/list/$', BlackoutList.as_view(), name='blackout-list'),
    url(r'^blackout/info/(?P<pk>\d+)/$', BlackoutInfo.as_view(), name='blackout-info'),
    url(r'^blackout/create/$', BlackoutCreate.as_view(), name='blackout-create'),
    url(r'^blackout/update/(?P<pk>\d+)/$', BlackoutUpdate.as_view(), name='blackout-update'),
    url(r'^blackout/delete/(?P<pk>\d+)/$', BlackoutDelete.as_view(), name='blackout-delete'),

    url(r'^params/list/$', ResParamsList.as_view(), name='params-list'),
    url(r'^params/update/(?P<pk>\d+)/$', ResParamsUpdate.as_view(), name='params-update'),

    url(r'^res/calendar/$', ReservationCalendar, name='reservation-calendar'),
    url(r'^res/calendar/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/$', ReservationCalendar, name='reservation-cal-day'),
    url(r'^duty/calendar/$', DutyCalendar, name='duty-calendar'),
    url(r'^duty/calendar/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]{1,2})/$', DutyCalendar, name='duty-cal-day'),

    url(r'^res/mlist/$', ReservationListMobile, name='mobile-res'),

    url(r'^res_feed/$', reservation_feed, name='reservation-feed'),
    url(r'^res_move/$', reservation_move, name='reservation-move'),
    url(r'^duty_feed/$', duty_feed, name='duty-feed'),
]

salt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, logout_then_login
from salt.views import dispatcher, salt_login, salt_password_change, admin_password_change

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^panel/', include('panel.urls', namespace="panel")),
    url(r'^camo/', include('camo.urls', namespace="camo")),
    url(r'^pdt/', include('pdt.urls', namespace="pdt")),
    url(r'^sms/', include('sms.urls', namespace="sms")),
    url(r'^ato/', include('ato.urls', namespace="ato")),
    url(r'^fin/', include('fin.urls', namespace="fin")),
    url(r'^fbo/', include('fbo.urls', namespace="fbo")),
    url(r'^res/', include('res.urls', namespace="res")),

    url(r'^login/$', salt_login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'dispatcher'}, name='logout'),
    url(r'^password/$', salt_password_change, {'post_change_redirect': 'dispatcher'}, name='pwd-change'),
    url(r'^adminpwd/(?P<user_id>\d+)/$', admin_password_change, name='admin-pwd-change'),
    url(r'^$', dispatcher, name='dispatcher'),
]

admin.site.site_header = 'Administracja systemu SALT'

salt/models.py
from django.db import models
from salt.forms import MyDurationFormField


class MyDurationField(models.DurationField):

    description = 'Simplified Duration Field'

    def formfield(self, **kwargs):
        defaults = {'form_class': MyDurationFormField}
        defaults.update(kwargs)
        return super(MyDurationField, self).formfield(**defaults)

salt/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.contrib.auth.views import login, password_change
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import update_session_auth_hash
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.utils.decorators import method_decorator
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from panel.models import FBOUser
from fbo.models import Parameter
from salt.forms import AdminPasswordChangeForm, ParameterChangeForm

def class_view_decorator(function_decorator):

    def simple_decorator(View):
        View.dispatch = method_decorator(function_decorator)(View.dispatch)
        return View

    return simple_decorator


# TODO - zablokować logowanie dla nieaktywnych
def salt_login(request, *args, **kwargs):
    if request.is_mobile:
        kwargs['template_name'] = 'registration/mlogin.html'
    else:
        kwargs['template_name'] = 'registration/login.html'
    return login(request, *args, **kwargs)


def salt_password_change(request, *args, **kwargs):
    kwargs['template_name'] = 'registration/pwd_change.html'
    return password_change(request, *args, **kwargs)


@user_passes_test(lambda u: u.is_staff)
def admin_password_change(request, user_id):

    user = FBOUser.objects.get(pk=user_id).user
    form = AdminPasswordChangeForm(request.POST or None, user=user)

    context = {}
    context['form'] = form
    context['page_title'] = 'Zmiana hasła'
    context['header_text'] = 'Zmiana hasła dla użytkownika %s' % user

    # Jeśli formularz został poprawnie wypełniony
    if form.is_valid():

        form.save()
        if user == request.user:
            update_session_auth_hash(request, user)

        return HttpResponseRedirect(reverse('fbo:user-list'))

    return render(request, 'registration/pwd_change.html', context)


def dispatcher(request):

    params = Parameter.objects.last()
    context={'mobile': request.is_mobile}
    context['infopriority'] = params.info_priority
    context['info'] = params.info_body
    context['infocontact'] = '\n<u>W razie problemów skontaktuj się z:</u>\n\n' +\
                             '<table><tr><td style="padding-right: 50px"><b>Agnieszka Pęksa</b></td>' + \
                             '<td><b>Michał Szamborski</b></td></tr>' + \
                             '<tr><td><a href="mailto:a.peksa@salt.aero">a.peksa@salt.aero</a></td>' +\
                             '<td><a href="mailto:michal.szamborski@salt.aero">michal.szamborski@salt.aero</a></td></tr>' +\
                             '<tr><td>509 054635</td>' +\
                             '<td>601 282808</td></tr></table>'
    if request.is_mobile:
        return render(request, 'mdispatcher.html', context)
    else:
        return render(request, 'dispatcher.html', context)


@class_view_decorator(user_passes_test(lambda u: u.is_staff))
class ParamsList (ListView):
    model = Parameter
    template_name = 'fbo/list_template.html'

    def get_queryset(self):
        return Parameter.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ParamsList, self).get_context_data(**kwargs)
        context['page_title'] = 'Parametry'
        context['header_text'] = 'Parametry systemowe'
        context['empty_text'] = 'Brak parametrów.'

        # Lokalne menu
        local_menu = []
        local_menu.append({'text': 'Zmiana parametrów', 'path': reverse("fbo:parameters-update", args=[1])})
        context['local_menu'] = local_menu

        # Nagłówki tabeli
        header_list = []
        header_list.append({'header': 'Nazwa parametru'})
        header_list.append({'header': 'Wartość parametru'})
        context['header_list'] = header_list

        row_list = []
        object = self.object_list.last()
        for model_field in Parameter._meta.get_fields():
            fields = []
            if model_field.name != 'id':
                fields.append({'name': model_field.name, 'value': model_field.verbose_name, 'bold': True})
                fields.append({'name': model_field.name, 'value': getattr(object, model_field.name)})
                row_list.append({'fields': fields})
        context['row_list'] = row_list
        context['no_paging'] = True

        return context


@class_view_decorator(user_passes_test(lambda u: u.is_staff))
class ParamsUpdate (UpdateView):
    model = Parameter
    template_name = 'fbo/params_template.html'

    def get_context_data(self, **kwargs):
        context = super(ParamsUpdate, self).get_context_data(**kwargs)
        context['page_title'] = 'Parametry systemu'
        context['header_text'] = 'Modyfikacja parametrów systemowych'
        return context

    def get_form_class(self, **kwargs):
        form_class = ParameterChangeForm
        return form_class

    def get_success_url(self):
        return reverse('fbo:parameters')

salt/templates/res/delete_template.html
{% extends 'res/res_template.html' %}

{% block title %}{{ page_title|default_if_none:"Usuwanie" }}{% endblock %}

{% if submenu_template %}
    {% block submenu %}
        {% include submenu_template|default:"res/empty_submenu.html" %}
    {% endblock %}
{% endif  %}

{% block content %}

    {% if submenu_template %}
        <div class="pure-u-5-6">
    {% else %}
        <div class="pure-u-1-1">
    {% endif %}

        <h2>{{ header_text|default_if_none:"Usunięcie obiektu" }}</h2>

        <p class="del-text">Potwierdź usunięcie <b>{{ object }}</b></p>

        {% if description  %}
            <p class="del-info">{{ description|linebreaksbr }}</p>
        {% endif %}

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="pure-button" style="margin-right: 10px">Usuń</button>
            <a class="pure-button" href="javascript:history.go(-1)">Anuluj</a>
        </form>

    </div>

{% endblock %}

salt/templates/res/mres_delete.html
{% extends 'salt_mobile.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block header %}Rezerwacje{% endblock %}

{% block content %}

    <p class="del-text" style="font-size: 18px"><b>Potwierdź usunięcie:</b></p>

    <p style="color: darkred; padding-left: 20px">
    <b>{{ object_name }}</b><br>
    Od: {{ object.start_time }}<br>
    Do: {{ object.end_time }}</p>

    {% if description  %}
        <p class="del-info" style="padding-left: 20px"><i>{{ description|linebreaksbr }}</i></p>
    {% endif %}

    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <fieldset class="ui-grid-a">
            <div class=" ui-block-a"><a type="submit" class="ui-btn ui-btn-icon-left ui-icon-arrow-l" href={% url 'res:mobile-res' %}>Powrót</a></div>
            <div class=" ui-block-b"><button type="submit" class="ui-btn ui-btn-icon-right ui-icon-delete">Usuń</button></div>
        </fieldset>
    </form>

{% endblock %}

salt/templates/res/mres_list.html
{% extends 'salt_mobile.html' %}

{% block title %}{{ page_title }}{% endblock %}

{% block header %}Rezerwacje{% endblock %}

{% block content %}

    <fieldset class="ui-grid-a">
        <div class=" ui-block-a"><a data-role="button" class="ui-btn ui-btn-icon-left ui-icon-clock" href="{{ local_menu.create_path }}" data-ajax="false">Rezerwuj</a></div>
        <div class=" ui-block-b"><a data-role="button" class="ui-btn ui-btn-icon-right ui-icon-calendar" href="{{ local_menu.cal_path }}" data-ajax="false">Kalendarz</a></div>
    </fieldset>

    {% if row_list %}
        <table id="mobile-table">
            {% for row in row_list %}
                <tr>
                    <td>
                        {{ row.fields.line1 | safe }}<br>
                        {{ row.fields.line2 | safe }}<br>
                        {% if row.fields.line3 %}{{ row.fields.line3 }}<br>{% endif %}
                        {% if row.fields.line4 %}<i>{{ row.fields.line4 }}</i>{% endif %}
                    </td>
                    <td>
                        {% if row.fields.pdt_link %}
                            <a data-role="button" class="ui-res" href="{{ row.fields.pdt_link }}" data-ajax="false">PDT</a>
                        {% endif %}
                        <a data-role="button" class="ui-res" href="{{ row.fields.edit_link }}" data-ajax="false">Zmień</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="info-text" style="text-align: center"><br><i>{{ empty_text|default_if_none:"Brak obiektów." }}</i></p>
    {% endif %}

{% endblock %}

salt/templates/res/mres_modify.html
{% extends 'salt_mobile.html' %}

{% load staticfiles %}

{% block title %}{{ page_title }}{% endblock %}

{% block header %}Rezerwacja{% endblock %}

{% block content %}

    <form action="" method="POST" data-ajax="false">

        {% csrf_token %}

        <div class="ui-field-contain">

            <div style="display:none;">
                <label for="{{ form.owner.id_for_label }}">{{ form.owner.label }}</label>
                {{ form.owner }}
            </div>

            <div class="fieldWrapper">
                <label style="display: none" for="{{ form.aircraft.id_for_label }}">{{ form.aircraft.label }}</label>
                {{ form.aircraft }}
            </div>
            <div class="fieldWrapper">
                <label style="display: none" for="{{ form.planned_type.id_for_label }}">{{ form.planned_type.label }}</label>
                {{ form.planned_type }}
            </div>
            <div class="fieldWrapper">
                <label style="display: none" for="{{ form.participant.id_for_label }}">{{ form.participant.label }}</label>
                {{ form.participant }}
            </div>
            <fieldset class="ui-grid-a">
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.start_time.id_for_label }}">{{ form.start_time.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.start_time }}</div>
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.end_time.id_for_label }}">{{ form.end_time.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.end_time }}</div>
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.planned_time.id_for_label }}">{{ form.planned_time.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.planned_time }}</div>
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.loc_start.id_for_label }}">{{ form.loc_start.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.loc_start }}</div>
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.loc_stop.id_for_label }}">{{ form.loc_stop.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.loc_stop }}</div>
                <div class="ui-block-a">
                    <label style="margin-top: 10px" for="{{ form.loc_end.id_for_label }}">{{ form.loc_end.label }}:</label>
                </div>
                <div class="ui-block-b">{{ form.loc_end }}</div>
            </fieldset>

            <div class="fieldWrapper">
                <label style="display: none" for="{{ form.remarks.id_for_label }}">{{ form.remarks.label }}</label>
                {{ form.remarks }}
            </div>

            {% if form.non_field_errors %}
                <div class="mobile-form-errors">
                    {% for error in form.non_field_errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                </div>
            {% else %}
                <br>
            {% endif %}

            {% if not update %}
                <fieldset class="ui-grid-a">
                    <div class=" ui-block-a"><a type="submit" class="ui-btn ui-btn-icon-left ui-icon-arrow-l" href="javascript:$.mobile.back()">Wróć</a></div>
                    <div class=" ui-block-b"><button type="submit" class="ui-btn ui-btn-icon-right ui-icon-check">Dodaj</button></div>
                </fieldset>
            {% else %}
                <fieldset class="ui-grid-b" style="font-size: 14px">
                    <div class=" ui-block-a"><a type="submit" class="ui-btn ui-btn-icon-left ui-icon-arrow-l" href="javascript:$.mobile.back()">Wróć</a></div>
                    <div class=" ui-block-b"><button type="submit" class="ui-btn ui-btn-icon-right ui-icon-check">Zmień</button></div>
                    <div class=" ui-block-c"><a type="submit" class="ui-btn ui-btn-icon-right ui-icon-delete" href={% url 'res:reservation-delete' pk %}>Usuń</a></div>
                </fieldset>
            {% endif %}

        </div>

    </form>

    <script type="text/javascript">

        $(document).on( "pageshow", function( event, ui ) {

            var activePage = $.mobile.pageContainer.pagecontainer( "getActivePage" );

            var start = $('#id_start_time', activePage);
            var end = $('#id_end_time', activePage);
            var duration = $('#id_planned_time', activePage);

            jQuery.datetimepicker.setLocale('pl');

            picker_conf = {
                format:'d.m.Y H:i',
                lang:'pl',
                step:30
            };

            change_duration = function()
            {
                var d1 = new Date(start.val().substring(6,10)+'-'+start.val().substring(3,5)+'-'+start.val().substring(0,2)+'T'+start.val().substring(11,16));
                var d2 = new Date(end.val().substring(6,10)+'-'+end.val().substring(3,5)+'-'+end.val().substring(0,2)+'T'+end.val().substring(11,16));

                if (d1.getTime() > 0 && d2.getTime() > 0)
                {
                    var seconds = ((d2 - d1) / 1000) - 30*60;
                    if (seconds < 0) {
                        seconds = 0
                    }
                    var hours = parseInt( seconds / 3600 ) % 24;
                    var minutes = parseInt( seconds / 60 ) % 60;

                    if (hours > 12) {
                        hours = 12;
                        minutes = 0;
                    }

                    var duration_str = (hours < 10 ? "0" + hours : hours) + ":" + (minutes < 10 ? "0" + minutes : minutes);
                    duration.val(duration_str);
                }
            };

            start.datetimepicker(picker_conf);
            start.change(change_duration);

            end.datetimepicker(picker_conf);
            end.change(change_duration);

            })

    </script>

{% endblock %}

salt/templates/res/res_template.html
{% extends 'salt_template.html' %}

{% block title %}REZERWACJE{% endblock %}

{% block module %}REZERWACJE I GRAFIKI{% endblock %}

{% block menu %}
    <li class="pure-menu-item"><a href="{% url 'res:reservation-calendar' %}" class="pure-menu-link">Kalendarz rezerwacji</a></li>
    <li class="pure-menu-item"><a href="{% url 'res:reservation-list' %}" class="pure-menu-link">
    {% if perms.res.res_admin %}
        Lista rezerwacji
    {% else %}
        Moje rezerwacje
    {% endif %}
    </a></li>
    {% if user.fbouser.infos %}
        <li class="pure-menu-item"><a href="{% url 'res:duty-calendar' %}" class="pure-menu-link">Grafik pilotów</a></li>
    {% endif %}
    {% if perms.res.res_admin %}
        <li class="pure-menu-item"><a href="{% url 'res:blackout-list' %}" class="pure-menu-link">Blokady SP</a></li>
        <li class="pure-menu-item"><a href="{% url 'res:resource-list' %}" class="pure-menu-link">Zasoby</a></li>
        <li class="pure-menu-item"><a href="{% url 'res:params-list' %}" class="pure-menu-link">Parametry SP</a></li>
    {% endif %}
{% endblock %}