ato/urls.py
from django.conf.urls import url
from ato.views import TrainingList, TrainingDetails, TrainingCreate, TrainingUpdate, TrainingDelete
from ato.views import PhaseDetails, PhaseCreate, PhaseUpdate, PhaseDelete
from ato.views import ExerciseDetails, ExerciseCreate, ExerciseUpdate, ExerciseDelete
from ato.views import InstructorList, InstructorCreate, InstructorUpdate, InstructorDelete
from ato.views import InstructorInfo, InstructorFlights, InstructorTrainings
from ato.views import StudentList, StudentCreate, StudentUpdate, StudentDelete
from ato.views import StudentInfo, StudentFlights, StudentTrainings
from ato.views import TrainingInstList, TrainingInstDetails, TrainingInstCreate, TrainingInstUpdate, TrainingInstDelete, TrainingInstPass
from ato.views import PhaseInstDetails, PhaseInstCreate, PhaseInstUpdate, PhaseInstDelete, PhaseInstPass
from ato.views import ExerciseInstDetails, ExerciseInstCreate, ExerciseInstUpdate, ExerciseInstDelete, ExerciseInstPass
from ato.views import ExerciseOperCreate, ExerciseOperUpdate, ExerciseOperDelete
from ato.views import CardEntryList, CardReport, CardEntryDetails, CardEntryCreate, CardEntryUpdate, CardEntryDelete


from ato.loaders import update_phases

urlpatterns = [

    url(r'^$', TrainingInstList.as_view(), name='training-inst-list'),
    url(r'^trinst/details/(?P<pk>\d+)/$', TrainingInstDetails.as_view(), name='training-inst-details'),
    url(r'^trinst/create/$', TrainingInstCreate, name='training-inst-create'),
    url(r'^trinst/update/(?P<pk>\d+)/$', TrainingInstUpdate.as_view(), name='training-inst-update'),
    url(r'^trinst/delete/(?P<pk>\d+)/$', TrainingInstDelete.as_view(), name='training-inst-delete'),
    url(r'^trinst/pass/(?P<pk>\d+)/$', TrainingInstPass, name='training-inst-pass'),

    url(r'^phinst/details/(?P<pk>\d+)/$', PhaseInstDetails.as_view(), name='phase-inst-details'),
    url(r'^phinst/create/(?P<training_inst_id>\d+)/$', PhaseInstCreate.as_view(), name='phase-inst-create'),
    url(r'^phinst/update/(?P<pk>\d+)/$', PhaseInstUpdate.as_view(), name='phase-inst-update'),
    url(r'^phinst/delete/(?P<pk>\d+)/$', PhaseInstDelete.as_view(), name='phase-inst-delete'),
    url(r'^phinst/pass/(?P<pk>\d+)/$', PhaseInstPass, name='phase-inst-pass'),

    url(r'^exinst/details/(?P<pk>\d+)/$', ExerciseInstDetails.as_view(), name='exercise-inst-details'),
    url(r'^exinst/create/(?P<phase_inst_id>\d+)/$', ExerciseInstCreate.as_view(), name='exercise-inst-create'),
    url(r'^exinst/update/(?P<pk>\d+)/$', ExerciseInstUpdate.as_view(), name='exercise-inst-update'),
    url(r'^exinst/delete/(?P<pk>\d+)/$', ExerciseInstDelete.as_view(), name='exercise-inst-delete'),
    url(r'^exinst/pass/(?P<pk>\d+)/$', ExerciseInstPass, name='exercise-inst-pass'),

    url(r'^exoper/create/(?P<exercise_inst_id>\d+)/$', ExerciseOperCreate, name='exercise-oper-create'),
    url(r'^exoper/update/(?P<pk>\d+)/$', ExerciseOperUpdate.as_view(), name='exercise-oper-update'),
    url(r'^exoper/delete/(?P<pk>\d+)/$', ExerciseOperDelete.as_view(), name='exercise-oper-delete'),

    url(r'^card/list/(?P<training_inst_id>\d+)/$', CardEntryList.as_view(), name='card-entry-list'),
    url(r'^card/report/(?P<training_inst_id>\d+)/$', CardReport.as_view(), name='card-report'),
    url(r'^card/details/(?P<pk>\d+)/$', CardEntryDetails.as_view(), name='card-entry-details'),
    url(r'^card/create/(?P<training_inst_id>\d+)/$', CardEntryCreate.as_view(), name='card-entry-create'),
    url(r'^card/update/(?P<pk>\d+)/$', CardEntryUpdate.as_view(), name='card-entry-update'),
    url(r'^card/delete/(?P<pk>\d+)/$', CardEntryDelete.as_view(), name='card-entry-delete'),

    url(r'^training/list/$', TrainingList.as_view(), name='training-list'),
    url(r'^training/details/(?P<pk>\d+)/$', TrainingDetails.as_view(), name='training-details'),
    url(r'^training/create/$', TrainingCreate.as_view(), name='training-create'),
    url(r'^training/update/(?P<pk>\d+)/$', TrainingUpdate.as_view(), name='training-update'),
    url(r'^training/delete/(?P<pk>\d+)/$', TrainingDelete.as_view(), name='training-delete'),

    url(r'^phase/details/(?P<pk>\d+)/$', PhaseDetails.as_view(), name='phase-details'),
    url(r'^phase/create/(?P<training_id>\d+)/$', PhaseCreate.as_view(), name='phase-create'),
    url(r'^phase/update/(?P<pk>\d+)/$', PhaseUpdate.as_view(), name='phase-update'),
    url(r'^phase/delete/(?P<pk>\d+)/$', PhaseDelete.as_view(), name='phase-delete'),

    url(r'^exercise/details/(?P<pk>\d+)/$', ExerciseDetails.as_view(), name='exercise-details'),
    url(r'^exercise/create/(?P<phase_id>\d+)/$', ExerciseCreate.as_view(), name='exercise-create'),
    url(r'^exercise/update/(?P<pk>\d+)/$', ExerciseUpdate.as_view(), name='exercise-update'),
    url(r'^exercise/delete/(?P<pk>\d+)/$', ExerciseDelete.as_view(), name='exercise-delete'),

    url(r'^instructor/list/$', InstructorList.as_view(), name='instr-list'),
    url(r'^instructor/info/(?P<pk>\d+)/$', InstructorInfo.as_view(), name='instr-info'),
    url(r'^instructor/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', InstructorTrainings.as_view(), name='instr-trainings'),
    url(r'^instructor/flights/(?P<pk>\d+)/$', InstructorFlights.as_view(), name='instr-flights'),
    url(r'^instructor/create/$', InstructorCreate.as_view(), name='instr-create'),
    url(r'^instructor/update/(?P<pk>\d+)/$', InstructorUpdate.as_view(), name='instr-update'),
    url(r'^instructor/delete/(?P<pk>\d+)/$', InstructorDelete.as_view(), name='instr-delete'),

    url(r'^student/list/$', StudentList.as_view(), name='student-list'),
    url(r'^student/info/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-info'),
    url(r'^student/flights/(?P<pk>\d+)/$', StudentFlights.as_view(), name='student-flights'),
    url(r'^student/account/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-account'),
    url(r'^student/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', StudentTrainings.as_view(), name='student-trainings'),
    url(r'^student/create/$', StudentCreate.as_view(), name='student-create'),
    url(r'^student/update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student-update'),
    url(r'^student/delete/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student-delete'),

    url(r'^_update/$', update_phases, name='update-phases'),

]

camo/urls.py
from django.conf.urls import url

from camo.views import AircraftList, AircraftCreate, AircraftUpdate, AircraftDelete, AircraftClone, AircraftARC
from camo.views import AircraftFuel, AircraftFuelUpdate, AircraftMsg, AircraftMsgUpdate
from camo.views import AircraftInfo, AircraftPOTs, AircraftParts, AircraftOrders, AircraftOpers, AircraftMods, AircraftWBs
from camo.views import AircraftStatements, MSDetails, MSCreate, MSUpdate, MSDelete
from camo.views import PartList, PartCreate, PartUpdate, PartDelete, PartPurge
from camo.views import PartInfo, PartHistory, PartPOTs, PartDirs, PartSBs, PartLLP, PartOvhs
from camo.views import AssignExistingPartCreate, AssignNewPartCreate, AssignmentUpdate, AssignmentDelete
from camo.views import POTGroupCreate, POTGroupClone, POTGroupUpdate, POTGroupDelete
from camo.views import POTGroupInfo, POTGroupEvents
from camo.views import POTEventDetails, POTEventCreate, POTEventUpdate, POTEventDelete
from camo.views import ATAList, ATADetails, ATACreate, ATAUpdate, ATADelete
from camo.views import WorkOrderCreate, WorkOrderList, WorkOrderDetails, WorkOrderClose, CRSCreate
from camo.views import ModificationDetails, ModificationCreate, ModificationDelete, ModificationUpdate
from camo.views import WBDetails, WBCreate, WBUpdate, WBDelete
from camo.views import OperDetails, OperCreate, OperUpdate, OperDelete
from camo.views import PDTControlList, PDTControlInfo, PDTControlUpdate, PDTControlDelete, PDTCheck
from camo.views import PDTControlOperations, PDTOperCreate, PDTOperUpdate, PDTOperDelete

from panel.views import MobilePDTClose

from camo.loaders import POTGroupUpload, POTGroupImport
from camo.loaders import POTEventUpload, POTEventImport

from camo.loaders import update, check_history

from camo.reports import ReportParts, ReportARC

urlpatterns = [
    url(r'^$', AircraftList.as_view(), name='aircraft-list'),
    url(r'^aircraft/create/$', AircraftCreate, name='aircraft-create'),
    url(r'^aircraft/update/(?P<pk>\d+)/$', AircraftUpdate.as_view(), name='aircraft-update'),
    url(r'^aircraft/fuelupdate/(?P<pk>\d+)/$', AircraftFuelUpdate.as_view(), name='aircraft-fuel-update'),
    url(r'^aircraft/msgupdate/(?P<pk>\d+)/$', AircraftMsgUpdate.as_view(), name='aircraft-msg-update'),
    url(r'^aircraft/delete/(?P<pk>\d+)/$', AircraftDelete.as_view(), name='aircraft-delete'),
    url(r'^aircraft/clone/$', AircraftClone, name='aircraft-clone'),
    url(r'^aircraft/info/(?P<pk>\d+)/$', AircraftInfo.as_view(), name='aircraft-info'),
    url(r'^aircraft/parts/(?P<pk>\d+)/$', AircraftParts.as_view(), name='aircraft-parts'),
    url(r'^aircraft/pots/(?P<pk>\d+)/$', AircraftPOTs.as_view(), name='aircraft-pots'),
    url(r'^aircraft/orders/(?P<pk>\d+)/$', AircraftOrders.as_view(), name='aircraft-orders'),
    url(r'^aircraft/opers/(?P<pk>\d+)/$', AircraftOpers.as_view(), name='aircraft-opers'),
    url(r'^aircraft/mods/(?P<pk>\d+)/$', AircraftMods.as_view(), name='aircraft-mods'),
    url(r'^aircraft/wbs/(?P<pk>\d+)/$', AircraftWBs.as_view(), name='aircraft-wbs'),
    url(r'^aircraft/ms/(?P<pk>\d+)/$', AircraftStatements.as_view(), name='aircraft-ms'),
    url(r'^aircraft/arc/(?P<pk>\d+)/$', AircraftARC.as_view(), name='aircraft-arc'),
    url(r'^aircraft/fuel/(?P<pk>\d+)/$', AircraftFuel.as_view(), name='aircraft-fuel'),
    url(r'^aircraft/msg/(?P<pk>\d+)/$', AircraftMsg.as_view(), name='aircraft-msg'),

    url(r'^part/list/$', PartList.as_view(), name='part-list'),
    url(r'^part/create/$', PartCreate.as_view(), name='part-create'),
    url(r'^part/update/(?P<pk>\d+)/$', PartUpdate.as_view(), name='part-update'),
    url(r'^part/delete/(?P<pk>\d+)/$', PartDelete.as_view(), name='part-delete'),
    url(r'^part/info/(?P<pk>\d+)/$', PartInfo.as_view(), name='part-info'),
    url(r'^part/history/(?P<pk>\d+)/$', PartHistory.as_view(), name='part-history'),
    url(r'^part/pots/(?P<pk>\d+)/$', PartPOTs.as_view(), name='part-pots'),
    url(r'^part/dirs/(?P<pk>\d+)/$', PartDirs.as_view(), name='part-dirs'),
    url(r'^part/sbs/(?P<pk>\d+)/$', PartSBs.as_view(), name='part-sbs'),
    url(r'^part/llp/(?P<pk>\d+)/$', PartLLP.as_view(), name='part-llp'),
    url(r'^part/ovhs/(?P<pk>\d+)/$', PartOvhs.as_view(), name='part-ovhs'),
    url(r'^part/purge/(?P<type>\w+)/(?P<part_id>\d+)/$', PartPurge, name='part-purge'),

    url(r'^assignpart/create/(?P<aircraft_id>\d+)/$', AssignExistingPartCreate, name='assign-existing-part-create'),
    url(r'^assignpart/new/(?P<aircraft_id>\d+)/$', AssignNewPartCreate, name='assign-new-part-create'),
    url(r'^assignpart/update/(?P<assignment_id>\d+)/$', AssignmentUpdate, name='assign-part-update'),
    url(r'^assignpart/delete/(?P<assignment_id>\d+)/$', AssignmentDelete, name='assign-part-delete'),

    url(r'^potgroup/create/(?P<type>\w+)/(?P<part_id>\d+)/$', POTGroupCreate.as_view(), name='pot-group-create'),
    url(r'^potgroup/upload/(?P<type>\w+)/(?P<part_id>\d+)/$', POTGroupUpload, name='pot-group-upload'),
    url(r'^potgroup/import/(?P<type>\w+)/(?P<part_id>\d+)/$', POTGroupImport, name='pot-group-import'),
    url(r'^potgroup/clone/(?P<potgroup_id>\d+)/$', POTGroupClone, name='pot-group-clone'),
    url(r'^potgroup/update/(?P<type>\w+)/(?P<pk>\d+)/$', POTGroupUpdate.as_view(), name='pot-group-update'),
    url(r'^potgroup/delete/(?P<pk>\d+)/$', POTGroupDelete.as_view(), name='pot-group-delete'),
    url(r'^potgroup/info/(?P<pk>\d+)/$', POTGroupInfo.as_view(), name='pot-group-info'),
    url(r'^potgroup/events/(?P<pk>\d+)/$', POTGroupEvents.as_view(), name='pot-group-events'),

    url(r'^potevent/details/(?P<pk>\d+)/$', POTEventDetails.as_view(), name='pot-event-details'),
    url(r'^potevent/create/(?P<pot_group_id>\d+)/$', POTEventCreate.as_view(), name='pot-event-create'),
    url(r'^potevent/upload/(?P<pot_group_id>\d+)/$', POTEventUpload, name='pot-event-upload'),
    url(r'^potevent/import/(?P<pot_group_id>\d+)/$', POTEventImport, name='pot-event-import'),
    url(r'^potevent/update/(?P<pk>\d+)/$', POTEventUpdate.as_view(), name='pot-event-update'),
    url(r'^potevent/delete/(?P<pk>\d+)/$', POTEventDelete.as_view(), name='pot-event-delete'),

    url(r'^ata/list/$', ATAList.as_view(), name='ata-list'),
    url(r'^ata/details/(?P<pk>\d+)/$', ATADetails.as_view(), name='ata-details'),
    url(r'^ata/create/$', ATACreate.as_view(), name='ata-create'),
    url(r'^ata/update/(?P<pk>\d+)/$', ATAUpdate.as_view(), name='ata-update'),
    url(r'^ata/delete/(?P<pk>\d+)/$', ATADelete.as_view(), name='ata-delete'),

    url(r'^order/list/$', WorkOrderList.as_view(), name='order-list'),
    url(r'^order/details/(?P<pk>\d+)/$', WorkOrderDetails.as_view(), name='order-details'),
    url(r'^order/close/(?P<work_order_id>\d+)/$', WorkOrderClose, name='order-close'),
    url(r'^order/create/(?P<aircraft_id>\d+)/$', WorkOrderCreate, name='order-create'),

    url(r'^crs/create/(?P<work_order_id>\d+)/$', CRSCreate, name='crs-create'),

    url(r'^modification/details/(?P<pk>\d+)/$', ModificationDetails.as_view(), name='modification-details'),
    url(r'^modification/create/(?P<aircraft_id>\d+)/$', ModificationCreate.as_view(), name='modification-create'),
    url(r'^modification/update/(?P<pk>\d+)/$', ModificationUpdate.as_view(), name='modification-update'),
    url(r'^modification/delete/(?P<pk>\d+)/$', ModificationDelete.as_view(), name='modification-delete'),

    url(r'^wb/details/(?P<pk>\d+)/$', WBDetails.as_view(), name='wb-details'),
    url(r'^wb/create/(?P<aircraft_id>\d+)/$', WBCreate.as_view(), name='wb-create'),
    url(r'^wb/update/(?P<pk>\d+)/$', WBUpdate.as_view(), name='wb-update'),
    url(r'^wb/delete/(?P<pk>\d+)/$', WBDelete.as_view(), name='wb-delete'),

    url(r'^ms/details/(?P<pk>\d+)/$', MSDetails.as_view(), name='ms-details'),
    url(r'^ms/create/(?P<aircraft_id>\d+)/$', MSCreate.as_view(), name='ms-create'),
    url(r'^ms/update/(?P<pk>\d+)/$', MSUpdate.as_view(), name='ms-update'),
    url(r'^ms/delete/(?P<pk>\d+)/$', MSDelete.as_view(), name='ms-delete'),

    url(r'^oper/details/(?P<pk>\d+)/$', OperDetails.as_view(), name='oper-details'),
    url(r'^oper/create/(?P<aircraft_id>\d+)/$', OperCreate.as_view(), name='oper-create'),
    url(r'^oper/update/(?P<pk>\d+)/$', OperUpdate.as_view(), name='oper-update'),
    url(r'^oper/delete/(?P<pk>\d+)/$', OperDelete.as_view(), name='oper-delete'),

    url(r'^pdt/list/$', PDTControlList.as_view(), name='pdt-list'),
    url(r'^pdt/info/(?P<pk>\d+)/$', PDTControlInfo.as_view(), name='pdt-info'),
    url(r'^pdt/oper/(?P<pk>\d+)/$', PDTControlOperations.as_view(), name='pdt-oper'),
    url(r'^pdt/update/(?P<pk>\d+)/$', PDTControlUpdate.as_view(), name='pdt-update'),
    url(r'^pdt/delete/(?P<pk>\d+)/$', PDTControlDelete.as_view(), name='pdt-delete'),
    url(r'^pdt/close/(?P<pdt_id>\d+)/$', MobilePDTClose, name='pdt-close'),
    url(r'^pdt/check/(?P<pdt_id>\d+)/$', PDTCheck, name='pdt-check'),

    url(r'^pdtoper/create/(?P<pdt_id>\d+)/$', PDTOperCreate.as_view(), name='pdt-oper-create'),
    url(r'^pdtoper/update/(?P<pk>\d+)/$', PDTOperUpdate.as_view(), name='pdt-oper-update'),
    url(r'^pdtoper/delete/(?P<pk>\d+)/$', PDTOperDelete.as_view(), name='pdt-oper-delete'),

    url(r'^report/parts/(?P<aircraft_id>\d+)/$', ReportParts, name='report-parts'),
    url(r'^report/arc/(?P<aircraft_id>\d+)/$', ReportARC, name='report-arc'),

    url(r'^_update/$', update, name='update-aircraft'),
    url(r'^_check/$', check_history, name='check-pdts'),

]

salt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, logout_then_login
from salt.views import dispatcher, salt_login, salt_password_change, admin_password_change

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^panel/', include('panel.urls', namespace="panel")),
    url(r'^camo/', include('camo.urls', namespace="camo")),
    url(r'^pdt/', include('pdt.urls', namespace="pdt")),
    url(r'^sms/', include('sms.urls', namespace="sms")),
    url(r'^ato/', include('ato.urls', namespace="ato")),
    url(r'^fin/', include('fin.urls', namespace="fin")),
    url(r'^fbo/', include('fbo.urls', namespace="fbo")),
    url(r'^res/', include('res.urls', namespace="res")),

    url(r'^login/$', salt_login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'dispatcher'}, name='logout'),
    url(r'^password/$', salt_password_change, {'post_change_redirect': 'dispatcher'}, name='pwd-change'),
    url(r'^adminpwd/(?P<user_id>\d+)/$', admin_password_change, name='admin-pwd-change'),
    url(r'^$', dispatcher, name='dispatcher'),
]

admin.site.site_header = 'Administracja systemu SALT'

salt/models.py
from django.db import models
from salt.forms import MyDurationFormField


class MyDurationField(models.DurationField):

    description = 'Simplified Duration Field'

    def formfield(self, **kwargs):
        defaults = {'form_class': MyDurationFormField}
        defaults.update(kwargs)
        return super(MyDurationField, self).formfield(**defaults)

salt/templates/camo/aircraft_clone.html
{% extends 'camo/camo_template.html' %}

{% block title %}Klonuj SP{% endblock %}

{% block content %}

    <div class="pure-u">

        <h2>Sklonuj statek powietrzny</h2>

        <form class="pure-form pure-form-aligned" action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr><td></td><td>
                <button type="submit" class="pure-button" style="margin-right: 10px">Sklonuj</button>
                <a class="pure-button" href="{% url "camo:aircraft-list" %}">Anuluj</a>
                </td></tr>
            </table>
        </form>

    </div>

{% endblock %}

salt/templates/camo/aircraft_submenu.html
<div class="pure-u-1-6">

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item {% if type == 'info' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-info' object.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ object }}</b></a></li>
            <li class="pure-menu-item {% if type == 'msg' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-msg' object.pk %}" class="pure-menu-link">Informacje dla pilotów</a></li>
            <li class="pure-menu-item {% if type == 'parts' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-parts' object.pk %}" class="pure-menu-link">Zabudowane części</a></li>
            <li class="pure-menu-item {% if type == 'pots' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-pots' object.pk %}" class="pure-menu-link">Najbliższe obsługi</a></li>
            <li class="pure-menu-item {% if type == 'orders' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-orders' object.pk %}" class="pure-menu-link">Wystawione zlecenia</a></li>
            <li class="pure-menu-item {% if type == 'opers' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-opers' object.pk %}" class="pure-menu-link">Lista operacji</a></li>
            <li class="pure-menu-item {% if type == 'mods' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-mods' object.pk %}" class="pure-menu-link">Modyfikacje i naprawy</a></li>
            <li class="pure-menu-item {% if type == 'wbs' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-wbs' object.pk %}" class="pure-menu-link">Raporty W&B</a></li>
            <li class="pure-menu-item {% if type == 'ms' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-ms' object.pk %}" class="pure-menu-link">Świadectwa MS</a></li>
            <li class="pure-menu-item {% if type == 'arc' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-arc' object.pk %}" class="pure-menu-link">Raport ARC</a></li>
            <li class="pure-menu-item {% if type == 'fuel' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:aircraft-fuel' object.pk %}" class="pure-menu-link">Paliwo</a></li>
        </ul>
    </div>

</div>

salt/templates/camo/group_submenu.html
<div class="pure-u-1-6">

    {% if object.part.current_assignment %}
    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-info' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ object.part.current_assignment.aircraft }}</b></a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-parts' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Zabudowane części</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-pots' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Najbliższe obsługi</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-orders' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Wystawione zlecenia</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-opers' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Lista operacji</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-mods' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Modyfikacje i naprawy</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-wbs' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Raporty W&B</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-ms' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Świadectwa MS</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:aircraft-arc' object.part.current_assignment.aircraft.pk %}" class="pure-menu-link">Raport ARC</a></li>
        </ul>
    </div>
    {% endif %}

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item">
                <a href="{% url 'camo:part-info' object.part.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ object.part.serial_no|truncatechars:15 }}</b></a></li>
            <li class="pure-menu-item">
                <a href="{% url 'camo:part-history' object.part.pk %}" class="pure-menu-link">Historia montażu</a></li>
            <li class="pure-menu-item {% if object.type == 'oth' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:part-pots' object.part.pk %}" class="pure-menu-link">Obsługi wg. POT</a></li>
            <li class="pure-menu-item {% if object.type == 'ad' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:part-dirs' object.part.pk %}" class="pure-menu-link">Dyrektywy</a></li>
            <li class="pure-menu-item {% if object.type == 'sb' %}pure-menu-selected{% endif %}">
                <a href="{% url 'camo:part-sbs' object.part.pk %}" class="pure-menu-link">Biuletyny</a></li>
            {% if object.part.lifecycle == 'ovh' %}
                <li class="pure-menu-item {% if object.type == 'ovh' %}pure-menu-selected{% endif %}">
                    <a href="{% url 'camo:part-ovhs' object.part.pk %}" class="pure-menu-link">Remonty</a></li>
            {% elif object.part.lifecycle == 'llp' %}
                <li class="pure-menu-item {% if object.type == 'llp' %}pure-menu-selected{% endif %}">
                    <a href="{% url 'camo:part-llp' object.part.pk %}" class="pure-menu-link">Planowy demontaż</a></li>
            {%  endif %}
        </ul>
    </div>

</div>