ato/urls.py
from django.conf.urls import url
from ato.views import TrainingList, TrainingDetails, TrainingCreate, TrainingUpdate, TrainingDelete
from ato.views import PhaseDetails, PhaseCreate, PhaseUpdate, PhaseDelete
from ato.views import ExerciseDetails, ExerciseCreate, ExerciseUpdate, ExerciseDelete
from ato.views import InstructorList, InstructorCreate, InstructorUpdate, InstructorDelete
from ato.views import InstructorInfo, InstructorFlights, InstructorTrainings
from ato.views import StudentList, StudentCreate, StudentUpdate, StudentDelete
from ato.views import StudentInfo, StudentFlights, StudentTrainings
from ato.views import TrainingInstList, TrainingInstDetails, TrainingInstCreate, TrainingInstUpdate, TrainingInstDelete, TrainingInstPass
from ato.views import PhaseInstDetails, PhaseInstCreate, PhaseInstUpdate, PhaseInstDelete, PhaseInstPass
from ato.views import ExerciseInstDetails, ExerciseInstCreate, ExerciseInstUpdate, ExerciseInstDelete, ExerciseInstPass
from ato.views import ExerciseOperCreate, ExerciseOperUpdate, ExerciseOperDelete
from ato.views import CardEntryList, CardReport, CardEntryDetails, CardEntryCreate, CardEntryUpdate, CardEntryDelete


from ato.loaders import update_phases

urlpatterns = [

    url(r'^$', TrainingInstList.as_view(), name='training-inst-list'),
    url(r'^trinst/details/(?P<pk>\d+)/$', TrainingInstDetails.as_view(), name='training-inst-details'),
    url(r'^trinst/create/$', TrainingInstCreate, name='training-inst-create'),
    url(r'^trinst/update/(?P<pk>\d+)/$', TrainingInstUpdate.as_view(), name='training-inst-update'),
    url(r'^trinst/delete/(?P<pk>\d+)/$', TrainingInstDelete.as_view(), name='training-inst-delete'),
    url(r'^trinst/pass/(?P<pk>\d+)/$', TrainingInstPass, name='training-inst-pass'),

    url(r'^phinst/details/(?P<pk>\d+)/$', PhaseInstDetails.as_view(), name='phase-inst-details'),
    url(r'^phinst/create/(?P<training_inst_id>\d+)/$', PhaseInstCreate.as_view(), name='phase-inst-create'),
    url(r'^phinst/update/(?P<pk>\d+)/$', PhaseInstUpdate.as_view(), name='phase-inst-update'),
    url(r'^phinst/delete/(?P<pk>\d+)/$', PhaseInstDelete.as_view(), name='phase-inst-delete'),
    url(r'^phinst/pass/(?P<pk>\d+)/$', PhaseInstPass, name='phase-inst-pass'),

    url(r'^exinst/details/(?P<pk>\d+)/$', ExerciseInstDetails.as_view(), name='exercise-inst-details'),
    url(r'^exinst/create/(?P<phase_inst_id>\d+)/$', ExerciseInstCreate.as_view(), name='exercise-inst-create'),
    url(r'^exinst/update/(?P<pk>\d+)/$', ExerciseInstUpdate.as_view(), name='exercise-inst-update'),
    url(r'^exinst/delete/(?P<pk>\d+)/$', ExerciseInstDelete.as_view(), name='exercise-inst-delete'),
    url(r'^exinst/pass/(?P<pk>\d+)/$', ExerciseInstPass, name='exercise-inst-pass'),

    url(r'^exoper/create/(?P<exercise_inst_id>\d+)/$', ExerciseOperCreate, name='exercise-oper-create'),
    url(r'^exoper/update/(?P<pk>\d+)/$', ExerciseOperUpdate.as_view(), name='exercise-oper-update'),
    url(r'^exoper/delete/(?P<pk>\d+)/$', ExerciseOperDelete.as_view(), name='exercise-oper-delete'),

    url(r'^card/list/(?P<training_inst_id>\d+)/$', CardEntryList.as_view(), name='card-entry-list'),
    url(r'^card/report/(?P<training_inst_id>\d+)/$', CardReport.as_view(), name='card-report'),
    url(r'^card/details/(?P<pk>\d+)/$', CardEntryDetails.as_view(), name='card-entry-details'),
    url(r'^card/create/(?P<training_inst_id>\d+)/$', CardEntryCreate.as_view(), name='card-entry-create'),
    url(r'^card/update/(?P<pk>\d+)/$', CardEntryUpdate.as_view(), name='card-entry-update'),
    url(r'^card/delete/(?P<pk>\d+)/$', CardEntryDelete.as_view(), name='card-entry-delete'),

    url(r'^training/list/$', TrainingList.as_view(), name='training-list'),
    url(r'^training/details/(?P<pk>\d+)/$', TrainingDetails.as_view(), name='training-details'),
    url(r'^training/create/$', TrainingCreate.as_view(), name='training-create'),
    url(r'^training/update/(?P<pk>\d+)/$', TrainingUpdate.as_view(), name='training-update'),
    url(r'^training/delete/(?P<pk>\d+)/$', TrainingDelete.as_view(), name='training-delete'),

    url(r'^phase/details/(?P<pk>\d+)/$', PhaseDetails.as_view(), name='phase-details'),
    url(r'^phase/create/(?P<training_id>\d+)/$', PhaseCreate.as_view(), name='phase-create'),
    url(r'^phase/update/(?P<pk>\d+)/$', PhaseUpdate.as_view(), name='phase-update'),
    url(r'^phase/delete/(?P<pk>\d+)/$', PhaseDelete.as_view(), name='phase-delete'),

    url(r'^exercise/details/(?P<pk>\d+)/$', ExerciseDetails.as_view(), name='exercise-details'),
    url(r'^exercise/create/(?P<phase_id>\d+)/$', ExerciseCreate.as_view(), name='exercise-create'),
    url(r'^exercise/update/(?P<pk>\d+)/$', ExerciseUpdate.as_view(), name='exercise-update'),
    url(r'^exercise/delete/(?P<pk>\d+)/$', ExerciseDelete.as_view(), name='exercise-delete'),

    url(r'^instructor/list/$', InstructorList.as_view(), name='instr-list'),
    url(r'^instructor/info/(?P<pk>\d+)/$', InstructorInfo.as_view(), name='instr-info'),
    url(r'^instructor/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', InstructorTrainings.as_view(), name='instr-trainings'),
    url(r'^instructor/flights/(?P<pk>\d+)/$', InstructorFlights.as_view(), name='instr-flights'),
    url(r'^instructor/create/$', InstructorCreate.as_view(), name='instr-create'),
    url(r'^instructor/update/(?P<pk>\d+)/$', InstructorUpdate.as_view(), name='instr-update'),
    url(r'^instructor/delete/(?P<pk>\d+)/$', InstructorDelete.as_view(), name='instr-delete'),

    url(r'^student/list/$', StudentList.as_view(), name='student-list'),
    url(r'^student/info/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-info'),
    url(r'^student/flights/(?P<pk>\d+)/$', StudentFlights.as_view(), name='student-flights'),
    url(r'^student/account/(?P<pk>\d+)/$', StudentInfo.as_view(), name='student-account'),
    url(r'^student/trainings/(?P<type>\w+)/(?P<pk>\d+)/$', StudentTrainings.as_view(), name='student-trainings'),
    url(r'^student/create/$', StudentCreate.as_view(), name='student-create'),
    url(r'^student/update/(?P<pk>\d+)/$', StudentUpdate.as_view(), name='student-update'),
    url(r'^student/delete/(?P<pk>\d+)/$', StudentDelete.as_view(), name='student-delete'),

    url(r'^_update/$', update_phases, name='update-phases'),

]

salt/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, logout_then_login
from salt.views import dispatcher, salt_login, salt_password_change, admin_password_change

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^panel/', include('panel.urls', namespace="panel")),
    url(r'^camo/', include('camo.urls', namespace="camo")),
    url(r'^pdt/', include('pdt.urls', namespace="pdt")),
    url(r'^sms/', include('sms.urls', namespace="sms")),
    url(r'^ato/', include('ato.urls', namespace="ato")),
    url(r'^fin/', include('fin.urls', namespace="fin")),
    url(r'^fbo/', include('fbo.urls', namespace="fbo")),
    url(r'^res/', include('res.urls', namespace="res")),

    url(r'^login/$', salt_login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'dispatcher'}, name='logout'),
    url(r'^password/$', salt_password_change, {'post_change_redirect': 'dispatcher'}, name='pwd-change'),
    url(r'^adminpwd/(?P<user_id>\d+)/$', admin_password_change, name='admin-pwd-change'),
    url(r'^$', dispatcher, name='dispatcher'),
]

admin.site.site_header = 'Administracja systemu SALT'

ato/models.py
# -*- coding: utf-8 -*-

import datetime
from django.db import models
from django.core.exceptions import ObjectDoesNotExist

from salt.models import MyDurationField


class Module(models.Model):

    class Meta:
        permissions = [('ato_reader', 'ATO - Dostęp do odczytu'),
                       ('ato_admin', 'ATO - Dostęp pełny')]

    module = models.BooleanField()


class Training(models.Model):
    code = models.CharField(max_length=10, verbose_name='Kod szkolenia')
    name = models.CharField(max_length=100, verbose_name='Nazwa szkolenia')
    date = models.DateField(blank=True, null=True, verbose_name='Data wprowadenia programu')
    description = models.TextField(blank=True, null=True, verbose_name='Opis szkolenia')

    def __str__(self):
        return self.code


class Phase(models.Model):
    training = models.ForeignKey(Training, verbose_name='Szkolenie')
    code = models.CharField(max_length=12, verbose_name='Kod zadania/fazy')
    name = models.CharField(max_length=120, verbose_name='Nazwa zadania/fazy')
    description = models.TextField(blank=True, null=True, verbose_name='Opis zadania/fazy')
    predecessor = models.ForeignKey('Phase', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Wymagane poprzednie zdanie/faza')
    min_time_instr = MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')
    min_time_solo = MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')

    def __str__(self):
        return "%s / %s" % (self.training.code, self.code)


class Exercise(models.Model):
    phase = models.ForeignKey(Phase, verbose_name='Zadanie/faza')
    code = models.CharField(max_length=12, verbose_name='Kod ćwiczenia')
    name = models.CharField(max_length=150, verbose_name='Nazwa ćwiczenia')
    description = models.TextField(blank=True, null=True, verbose_name='Opis ćwiczenia')
    restrictions = models.CharField(max_length=3, choices=[('TAK','TAK'), ('NIE','NIE')], default='NIE', verbose_name='Restrykcje na instruktora')
    predecessor = models.ForeignKey('Exercise', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Wymagane poprzednie ćwiczenie')
    min_time_instr = MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')
    min_time_solo = MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')
    min_num_instr = models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń z instr.')
    min_num_solo  = models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń solo')

    def __str__(self):
        return "%s / %s" % (self.phase, self.code)


class Student(models.Model):
    pilot = models.OneToOneField('panel.Pilot', on_delete=models.CASCADE, verbose_name='Pilot')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return self.pilot.__str__()


class Instructor(models.Model):
    pilot = models.OneToOneField('panel.Pilot', on_delete=models.CASCADE, verbose_name='Pilot')
    restrictions = models.CharField(max_length=3, choices=[('TAK','TAK'), ('NIE','NIE')], default='NIE', verbose_name='Restrykcje')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return self.pilot.__str__()


class Training_inst(models.Model):
    training = models.ForeignKey(Training, verbose_name='Szkolenie')
    student = models.ForeignKey(Student, verbose_name='Student')
    instructor = models.ForeignKey(Instructor, verbose_name='Instruktor prowadzący')
    start_date = models.DateField(verbose_name='Data rozpoczęcia')
    passed = models.CharField(max_length=3, choices=[('TAK','TAK'), ('NIE','NIE')], default='NIE', verbose_name='Ukończone')
    pass_date = models.DateField(blank=True, null=True, verbose_name='Data ukończenia')
    open =  models.BooleanField(default=True, verbose_name='Czy otwarte')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return u'%s dla %s' % (self.training.code, self.student)

    def time_instr(self):
        time_instr = datetime.timedelta(seconds=0)
        for phase in self.phase_inst_set.all():
            if phase.time_instr():
                time_instr += phase.time_instr()
        return time_instr

    def time_solo(self):
        time_solo = datetime.timedelta(seconds=0)
        for phase in self.phase_inst_set.all():
            if phase.time_solo():
                time_solo += phase.time_solo()
        return time_solo

    def status(self):
        num_passed, num = 0, 0
        for phase_inst in self.phase_inst_set.all():
            for exercise_inst in phase_inst.exercise_inst_set.all():
                num += 1
                num_passed += (1 if exercise_inst.passed=='TAK' else 0)

        if self.open:
            if self.passed == 'TAK':
                return "Ukończone"
            else:
                if num_passed == 0:
                    return "Nowe"
                elif num != 0:
                    return "W trakcie (%.1f%%)" % (num_passed*100/num)
                else:
                    return "W trakcie"
        else:
            return "Zamknięte"


class Phase_inst(models.Model):
    training_inst = models.ForeignKey(Training_inst, verbose_name='Szkolenie')
    code = models.CharField(max_length=12, verbose_name='Kod zadania/fazy')
    name = models.CharField(max_length=120, verbose_name='Nazwa zadania/fazy')
    description = models.TextField(blank=True, null=True, verbose_name='Opis zadania/fazy')
    predecessor = models.ForeignKey('Phase_inst', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Wymagane poprzednie zdanie/faza')
    min_time_instr = MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')
    min_time_solo = MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')
    passed = models.CharField(max_length=3, choices=[('TAK','TAK'), ('NIE','NIE')], default='NIE', verbose_name='Zaliczenie')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return "%s / %s" % (self.training_inst.training.code, self.code)

    def time_instr(self):
        time_instr = datetime.timedelta(seconds=0)
        for exercise in self.exercise_inst_set.all():
            if exercise.time_instr:
                time_instr += exercise.time_instr
        return time_instr

    def time_solo(self):
        time_solo = datetime.timedelta(seconds=0)
        for exercise in self.exercise_inst_set.all():
            if exercise.time_solo:
                time_solo += exercise.time_solo
        return time_solo


class Exercise_inst(models.Model):
    phase_inst = models.ForeignKey(Phase_inst, verbose_name='Zadanie/faza')
    code = models.CharField(max_length=12, verbose_name='Kod ćwiczenia')
    name = models.CharField(max_length=150, verbose_name='Nazwa ćwiczenia')
    description = models.TextField(blank=True, null=True, verbose_name='Opis ćwiczenia')
    restrictions = models.CharField(max_length=3, choices=[('TAK', 'TAK'), ('NIE', 'NIE')], default='NIE',
                                    verbose_name='Restrykcje na instruktora')
    predecessor = models.ForeignKey('Exercise_inst', blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Wymagane poprzednie ćwiczenie')
    min_time_instr = MyDurationField(blank=True, null=True, verbose_name='Min. czas z instr.')
    min_time_solo = MyDurationField(blank=True, null=True, verbose_name='Min. czas solo')
    min_num_instr = models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń z instr.')
    min_num_solo  = models.IntegerField(blank=True, null=True, verbose_name='Min. liczba powtórzeń solo')
    time_instr = MyDurationField(blank=True, null=True, verbose_name='Czas z instr.')
    time_solo = MyDurationField(blank=True, null=True, verbose_name='Czas solo')
    num_instr = models.IntegerField(default=0, verbose_name='Liczba powtórzeń z instr.')
    num_solo  = models.IntegerField(default=0, verbose_name='Liczba powtórzeń solo')
    passed = models.CharField(max_length=3, choices=[('TAK','TAK'), ('NIE','NIE')], default='NIE', verbose_name='Zaliczenie')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return "%s / %s" % (self.phase_inst, self.code)


class Exercise_oper(models.Model):
    exercise_inst = models.ForeignKey(Exercise_inst, verbose_name='Cwiczenie')
    operation = models.ForeignKey('panel.Operation', verbose_name='Operacja')
    solo = models.BooleanField(default=False, verbose_name='Lot solo')
    time_allocated = MyDurationField(default=datetime.timedelta(seconds=0), verbose_name='Czas ćwiczenia')
    num_allocated = models.IntegerField(default=0, verbose_name='Liczba powtórzeń ćwiczenia')
    remarks = models.TextField(blank=True, null=True, verbose_name='Uwagi')

    def __str__(self):
        return "Operacja z dnia: %s, %s - %s" % (self.operation.pdt.date, self.operation.loc_start, self.operation.loc_end)

    def save(self, *args, **kwargs):
        # sprawdź czy nowy rekord czy zmiana istniejącego #
        try:
            existing = Exercise_oper.objects.get(pk=self.pk)
        except ObjectDoesNotExist:
            existing = None

        # zaktualizuj liczniki w ćwiczeniu #
        if existing:
            if existing.solo:
                self.exercise_inst.time_solo -= existing.time_allocated
                self.exercise_inst.num_solo -= existing.num_allocated
            else:
                self.exercise_inst.time_instr -= existing.time_allocated
                self.exercise_inst.num_instr -= existing.num_allocated
        if self.solo:
            self.exercise_inst.time_solo = (self.exercise_inst.time_solo or datetime.timedelta(seconds=0)) + self.time_allocated
            self.exercise_inst.num_solo = (self.exercise_inst.num_solo or 0) + self.num_allocated
        else:

salt/models.py
from django.db import models
from salt.forms import MyDurationFormField


class MyDurationField(models.DurationField):

    description = 'Simplified Duration Field'

    def formfield(self, **kwargs):
        defaults = {'form_class': MyDurationFormField}
        defaults.update(kwargs)
        return super(MyDurationField, self).formfield(**defaults)

salt/templates/ato/ato_template.html
{% extends 'salt_template.html' %}

{% block title %}ATO{% endblock %}

{% block scripts %}{% endblock %}

{% block module %}SZKOLENIA LOTNICZE{% endblock %}

{% block menu %}
    <li class="pure-menu-item"><a href="{% url 'ato:training-inst-list' %}" class="pure-menu-link">Szkolenia</a></li>
    <li class="pure-menu-item"><a href="{% url 'ato:student-list' %}" class="pure-menu-link">Studenci</a></li>
    <li class="pure-menu-item"><a href="{% url 'ato:instr-list' %}" class="pure-menu-link">Instruktorzy</a></li>
    <li class="pure-menu-item"><a href="{% url 'ato:training-list' %}" class="pure-menu-link">Programy szkoleń</a></li>
{% endblock %}

salt/templates/ato/card.html
<!DOCTYPE html>

{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />

<html>
<head lang="pl">
    <meta charset="UTF-8">
    <title>Karta szkolenia</title>
</head>
<body>

<div class="noPrint">
    <a href="{% url "ato:card-entry-list" training_inst.pk %}"><button style="color: darkred" type="button">Powrót</button></a>
    <button type="button" style="color: darkred" onclick="window.print()">Drukuj</button>
</div>

<br>
<h3>KARTA PRZEBIEGU SZKOLENIA PRAKTYCZNEGO<br>{{ training_inst }}</h3>

{% if row_list %}
    <table id="ato-card-table">
        <tr>
            <th rowspan="2">Data</th>
            <th rowspan="2">Instruktor</th>
            <th rowspan="2">Zad / Faza</th>
            <th rowspan="2">Ćwiczenie</th>
            <th colspan="2">Dwuster</th>
            <th colspan="2">Samodzielnie</th>
            <th rowspan="2">Zaliczenie</th>
            <th rowspan="2">Uwagi</th>
        </tr>
        <tr>
            <th>Powt.</th>
            <th>Czas</th>
            <th>Powt.</th>
            <th>Czas</th>
        </tr>

        {% for row in row_list %}
            <tr>
                {% for field in row.fields %}
                    <td nowrap style="text-align: {{ field.just }}"
                        {% if forloop.counter < 5 or forloop.counter > 8 %}
                            rowspan = "2"
                        {% endif %}
                    >
                        {{ field.value | default:"&nbsp" | linebreaksbr | truncatechars:40 }}
                    </td>
                {% endfor %}
            </tr>
            <tr>
                {% for sum in row.sums %}
                    <td style="text-align: center">{{ sum.value }}</td>
                {% endfor %}
            </tr>
        {% endfor %}
    </table>

{% else %}
    <p class="info-text">{{ empty_text|default_if_none:"Brak wpisów." }}</p>
{% endif %}

<br>

salt/templates/ato/create_template.html
{% extends 'ato/ato_template.html' %}

{% block title %}{{ page_title|default_if_none:"Rejestacja" }}{% endblock %}

{% block content %}

    <div class="pure-u">

        <h2>{{ header_text|default_if_none:"Rejestracja nowego obiektu" }}</h2>

        <form class="pure-form pure-form-aligned" action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr><td></td><td>
                <button type="submit" class="pure-button" style="margin-right: 10px">Utwórz</button>
                <a class="pure-button" href="javascript:history.go(-1)">Anuluj</a>
                </td></tr>
            </table>
        </form>

    </div>

    {% block scripts %}{% endblock %}

{% endblock %}

salt/templates/ato/ex_oper_create.html
{% extends 'ato/create_template.html' %}

{% block scripts %}

    <script type="text/javascript">

        $('select#id_operation').change(function()
        {
            $('input#id_time_allocated').val($('input#id_time_oper' + $(this).val()).val());
            $('input#id_num_allocated').val($('input#id_num_oper' + $(this).val()).val());
            $('input#id_solo').val(($('input#id_solo_oper' + $(this).val()).val()=='True'));
            $('input#id_solo').prop('checked',($('input#id_solo_oper' + $(this).val()).val()=='True'))
        });

    </script>

{% endblock %}

salt/templates/ato/instr_submenu.html
<div class="pure-u-1-6">

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item {% if type == 'info' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:instr-info' instructor.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ instructor.pilot|truncatechars:19 }}</b></a></li>
            <li class="pure-menu-item {% if type == 'trainings' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:instr-trainings' 'open' instructor.pk %}" class="pure-menu-link">Aktualne szkolenia</a></li>
            <li class="pure-menu-item {% if type == 'completed' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:instr-trainings' 'closed' instructor.pk %}" class="pure-menu-link">Zakończone szkolenia</a></li>
            <li class="pure-menu-item {% if type == 'flights' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:instr-flights' instructor.pk %}" class="pure-menu-link">Loty szkoleniowe</a></li>
        </ul>
    </div>

    <br>
    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item">
                <a href="#" class="pure-menu-link pure-menu-title"><b>Przejdź do ...</b></a></li>
            <li class="pure-menu-item">
                <a href="{% url 'panel:pilot-info' instructor.pilot.pk %}" class="pure-menu-link">Profil pilota</a></li>
            <li class="pure-menu-item">
                <a href="{% url 'fbo:user-info' instructor.pilot.fbouser.pk %}" class="pure-menu-link">Profil użytkownika</a></li>
        </ul>
    </div>

</div>

salt/templates/ato/instructor_create.html
{% extends 'ato/create_template.html' %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $('#id_user').change(function(){
                $.ajax({
                    url: '{% url "ato:instructor-create" %}',
                    type: 'GET',
                    data: {user_id: $(this).find("option:selected").val()},
                    success: function(response){
                        $("#id_first_name").val(response['first_name']);
                        $("#id_name").val(response['name']);
                        $("#id_email").val(response['email']);
                    },
                    error: function(response){
                        $("#id_first_name").val('');
                        $("#id_name").val('');
                        $("#id_email").val('');
                    }
                });
            });
        });
    </script>
{%  endblock %}

salt/templates/ato/student_submenu.html
<div class="pure-u-1-6">

    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item {% if type == 'info' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:student-info' student.pk %}" class="pure-menu-link pure-menu-title">
                    <b>{{ student.pilot|truncatechars:19 }}</b></a></li>
            <li class="pure-menu-item {% if type == 'trainings' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:student-trainings' 'open' student.pk %}" class="pure-menu-link">Aktualne szkolenia</a></li>
            <li class="pure-menu-item {% if type == 'completed' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:student-trainings' 'closed' student.pk %}" class="pure-menu-link">Zakończone szkolenia</a></li>
            <li class="pure-menu-item {% if type == 'flights' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:student-flights' student.pk %}" class="pure-menu-link">Loty szkoleniowe</a></li>
            <li class="pure-menu-item {% if type == 'account' %}pure-menu-selected{% endif %}">
                <a href="{% url 'ato:student-account' student.pk %}" class="pure-menu-link pure-menu-disabled">Konto finansowe</a></li>
        </ul>
    </div>

    <br>
    <div class="pure-menu custom-restricted-width" style="margin-right: 20%; margin-top: 5%">
        <ul class="pure-menu-list">
            <li class="pure-menu-item">
                <a href="#" class="pure-menu-link pure-menu-title"><b>Przejdź do ...</b></a></li>
            <li class="pure-menu-item">
                <a href="{% url 'panel:pilot-info' student.pilot.pk %}" class="pure-menu-link">Profil pilota</a></li>
            {% if student.pilot.fbouser.contractor %}
                <li class="pure-menu-item">
                    <a href="{% url 'fin:contr-info' student.pilot.fbouser.contractor.pk %}" class="pure-menu-link">Profil kontrahenta</a></li>
            {% endif %}
            <li class="pure-menu-item">
                <a href="{% url 'fbo:user-info' student.pilot.fbouser.pk %}" class="pure-menu-link">Profil użytkownika</a></li>
        </ul>
    </div>

</div>